version: "3.7"

services:
  server:
    image: ghcr.io/linuxserver/plex:1.32.5.7349-8f4248874@sha256:78704387c81e54852011c97a28d392214b5d90432c720228b94cd5e71dc4b537
    restart: on-failure
    hostname: "kidii-plex-server_1"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-xGsr2bH_EESETz89JZ8w
    ports:
      - 32400:32400
      # Plex Companion
      - 3005:3005/tcp
      # Roku via Plex Companion
      - 8324:8324/tcp
      # Plex DLNA Server
      - 32469:32469/tcp
      - 1900:1900/udp
      # Network discovery
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/transcode:/transcode
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
