version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kidii-radarr_server_1
      APP_PORT: 7878
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/radarr:version-5.3.6@sha256:cd1f0409e88cb09bec8bfb44303e6fda77eeae3fb00cd57960a027851c24fcbd
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure

  mac:
    image: getumbrel/media-app-configurator:v1.0.0@sha256:e3d8b18e0186f76dd3f3d4acacc9101b4abbf302d8f2afbb47cdd3879b1a1008
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    environment:
      DOWNLOAD_CLIENT_API_URL: "http://kidii-radarr_server_1:7878/api/v3/downloadclient"
      ROOT_FOLDER_API_URL: "http://kidii-radarr_server_1:7878/api/v3/rootfolder"
      TRANSMISSION_HOST: "transmission_server_1"
      TRANSMISSION_PORT: 9091
      ROOT_FOLDER: "/downloads/movies"
