version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kidii-duplicacy_server_1
      APP_PORT: 3875

  server:
    image: cr.hotio.dev/hotio/duplicacy
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/cache:/cache
      - ${APP_DATA_DIR}/data/logs:/logs
    restart: on-failure
